CREATE TABLE label(id SERIAL PRIMARY KEY, name VARCHAR(20));
CREATE TABLE todo(id SERIAL PRIMARY KEY, content VARCHAR(100), labelId INTEGER REFERENCES Label(id));
CREATE TABLE users(id SERIAL PRIMARY KEY, name VARCHAR(20), password BYTEA);